const productsTypes = {
    GET_PRODUCTS:"GET_PRODUCTS",
    RESET_PRODUCTS_ARRAY:"RESET_PRODUCTS_ARRAY",
    GET_SEARCH_PRODUCTS:"GET_SEARCH_PRODUCTS",
    RESET_SEARCH_PRODUCTS_ARRAY:"RESET_SEARCH_PRODUCTS_ARRAY"
}

export default productsTypes;