const userTypes = {
    SET_CURRENT_USER:'SET_CURRENT_USER',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR',
    RESET_ALL_SUCCESS_STATES: 'RESET_ALL_SUCCESS_STATES'
}

export default userTypes;